### ISSUE TITLE
texture are display invert on south wall and east wall

### ISSUE THREAD

**Issue by Askandrie** [StephaneVogrig/10_cube3d#5]
![image](https://github.com/user-attachments/assets/52469f86-4a6a-4bfd-91be-03b5e09452ba)
this is the corner NE for exemple

**Comment by StephaneVogrig** [comment]
where is the map with this problem ? it's possible to have a map (textures) where the problem is more evident ?

**Comment by StephaneVogrig** [comment]
I made textures for see and the fix this bug. These are in the commit.
